# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "pt-br" # language to set into html tag, default is en

# User settings

author: Miller P. Magalhães
author-title: Back-end Developer
gravatar: de1a0c0c0d269a7e1f9ed401fab9933a
email: miller@mpdev.com.br
twitter: Millerp_
github: millerp
googleplus:
facebook: Millerp
linkedin: imillerp/pt
bio: "Brazilian developer. Game, music and technology lover."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 3
  - name: CSS 3
    level: 3
  - name: JavaScript
    level: 3
  - name: jQuery
    level: 3
  - name: Angular
    level: 4
  - name: Vue.js
    level: 1
  - name: Bootstrap
    level: 4
    
back-end:
  - name: PHP
    level: 4
  - name: Node.js
    level: 1
  - name: SQL
    level: 3
    
mobile:
  - name: Android
    level: 1
  - name: Apache Cordova
    level: 1
  - name: Ionic
    level: 2

db:
  - name: MySQL
    level: 3
  - name: PostgreSQL
    level: 2
  - name: MongoDB
    level: 2
  - name: SQL Server
    level: 4
  - name: NoSQL
    level: 3

devops:
  - name: Docker
    level: 4
  - name: Vagrant
    level: 3
  - name: Git
    level: 5
  - name: Continuous Integration
    level: 1
  - name: Continuous Delivery
    level: 1

methodologies:
  - name: Agile Methodologies
    level: 2
  - name: Scrum
    level: 2
    
others:
  - name: Web Services
    level: 5
  - name: REST
    level: 5
  - name: Symfony
    level: 3
  - name: Twig
    level: 4
  - name: Doctrine ORM
    level: 3
  - name: Laravel, Blade, Eloquent ORM
    level: 5
  - name: Ruby on Rails
    level: 3
  - name: MEAN StEack
    level: 2

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap]
